name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🔍 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run Home Assistant Add-on Lint
        # TODO: revert to a released version once the PR is merged
        # https://github.com/frenck/action-addon-linter/pull/172
        uses: frenck/action-addon-linter@refs/pull/172/merge
        with:
          path: "./${{ matrix.path }}"

      - name: 🚀 Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./${{ matrix.path }}/Dockerfile"
